SegaMania.WebUI/Controllers/ConsoleSegaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SegaMania.Data;
using SegaMania.WebUI.Models;
using SegaMania.Logic;

namespace SegaMania.WebUI.Controllers
{
    public class ConsoleSegaController : Controller
    {
        public ActionResult ToutesLesConsoles()
        {
            List<ConsoleSega> listConsoles = RequestManager.ListConsoles();
            return View(listConsoles);
        }

        public ActionResult DetailsConsole(string nomSeo)
        {
            var vm = RequestManager.DetailsConsole(nomSeo);
            return View(vm);
        }
    }
}

SegaMania.WebUI/Controllers/JeuController.cs
using SegaMania.Data;
using SegaMania.Logic;
using SegaMania.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SegaMania.WebUI.Controllers
{
    public class JeuController : Controller
    {
        public ActionResult ToutLesJeux()
        {
            List<ConsoleSega> listConsoles = RequestManager.ToutLesJeuxParConsole();
            return View(listConsoles);
        }

        public ActionResult DetailsJeu(string nomSeo)
        {
            var vm = RequestManager.DetailsJeu(nomSeo);
            return View(vm);
        }
    }
}

SegaMania.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SegaMania</title>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Livvic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Segamania", "Accueil", "Home", new { area = "" }, new { @class = "navbar-brand titleSegaMania" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Les jeux", "ToutLesJeux", "Jeu")</li>
                    <li>@Html.ActionLink("Les consoles", "ToutesLesConsoles", "ConsoleSega")</li>
                    <li>@Html.ActionLink("Contact", "index", "Contact")</li>
                    @Html.Action("MoteurDeRecherchePartial", "Home")
                    <li></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="titleCenter">&copy; @DateTime.Now.Year - SegaMania Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SegaMania.WebUI/Views/Shared/_MoteurDeRecherchePartial.cshtml
@model SegaMania.WebUI.Models.RechercheViewModel
@{
    ViewBag.Title = "_MoteurDeRecherchePartial";
}
<li>
    <div class="search-container">
        @using (Html.BeginForm("Recherche", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <input type="text" placeholder="Entrez votre recherche..." name="search">
            <button type="submit"><i class="glyphicon glyphicon-search"></i></button>
        }
    </div>
</li>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SegaMania.WebUI/Views/Shared/_TestPartial.cshtml

@{
    ViewBag.Title = "_TestPartial";
}

<div class="form-group">
    <div class="col-md-2">
        <input type="submit" class="btn btn-default" value="OK" name="recherche" id="recherche" />
    </div>
</div>
