SegaMania.WebUI/Controllers/ContactController.cs
using SegaMania.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace SegaMania.WebUI.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnvoyerEmail(string nom, string email, string message)
        {
            try
            {
                var mger = new EmailManager();
                mger.SendEmail(nom, message, email);
            }
            catch
            {
                return View("ErreurEnvoi");
            }
            return View("Merci");
        }
    }
}

SegaMania.WebUI/Views/Contact/ErreurEnvoi.cshtml

@{
    ViewBag.Title = "Echec de l'envoi";
}

<h2>Echec de l'envoi</h2>
<p>Nous sommes désolé, l'envoi de votre message a échoué, nous vous invitons à rééssayer.</p>


SegaMania.WebUI/Views/Contact/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Contactez nous !</h2>
@using (Html.BeginForm("EnvoyerEmail", "Contact", FormMethod.Post))
{
    <label>Nom:</label>
    <input name="nom" id="nom" required/>

    <label>Email:</label>
    <input name="email" id="email" required/>

    <label>Message:</label>
    <input name="message" id="message" required/>

    <input type="submit" value="Envoyer" />
}


SegaMania.WebUI/Views/Contact/Merci.cshtml

@{
    ViewBag.Title = "Merci";
}

<h2>Merci pour votre message</h2>
<p>Votre message a bien été envoyé, nous y répondons dès que possible.</p>
