SegaMania.WebUI/Controllers/CollectionController.cs
using SegaMania.Data;
using SegaMania.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SegaMania.WebUI.Controllers
{
    public class CollectionController : Controller
    {
        public ActionResult AjoutCollection(int id,string userId, string table)
        {
            if (table == "jeuAssoPersonne")
            {
                RequestManager.AjoutCollection(id, userId, "jeuAssoPersonne");
                return RedirectToAction("ToutLesJeux", "Jeu");
            }
                RequestManager.AjoutCollection(id, userId, "consoleAssoPersonne");
                return RedirectToAction("ToutesLesConsoles", "ConsoleSega");
        }
    }
}

SegaMania.WebUI/Controllers/JeuController.cs
using SegaMania.Data;
using SegaMania.Logic;
using SegaMania.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SegaMania.WebUI.Controllers
{
    public class JeuController : Controller
    {
        public ActionResult ToutLesJeux()
        {
            List<ConsoleSega> listConsoles = RequestManager.ToutLesJeuxParConsole();
            return View(listConsoles);
        }

        public ActionResult DetailsJeu(string nomSeo)
        {
            var vm = RequestManager.DetailsJeu(nomSeo);
            return View(vm);
        }
    }
}

SegaMania.WebUI/Views/Jeu/DetailsJeu.cshtml
@model SegaMania.Logic.JeuViewModel
@{
    ViewBag.Title = Model.JeuNom;
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-danger errorMessage">
        @TempData["Message"]
    </div>
}

<h2 class="titleCenter">@Model.JeuNom</h2>
<br />
<p class="descriptionItem">@Model.JeuDescription</p>
@if (Model.NombreAvisJeu > 0)
{
    <div class="divBold">Note du jeu : @Model.Note sur 5</div>
}
<div class="divBold">Nombre d'avis : @Model.NombreAvisJeu</div>
<div class="divBold">Sortie sur : @Model.NomConsole</div>
<div class="divBold">Date de sortie : @Model.JeuDateDeSortie.ToShortDateString()</div>
<br />

@if (Model.NombreAvisJeu > 0)
{
    @Html.ActionLink("Retrouvez les avis pour ce jeu", "ListAvis", "AvisJeu", new { nomSeo = Model.JeuNomSeo}, new { @class ="linkBloc"})
}
@Html.ActionLink("Laissez un avis pour ce jeu", "LaisserUnavis", "AvisJeu", new { nomSeo = Model.JeuNomSeo })

SegaMania.WebUI/Views/Jeu/ToutLesJeux.cshtml
@using Microsoft.AspNet.Identity
@using SegaMania.Logic
@model List<SegaMania.Data.ConsoleSega>
@{
    ViewBag.Title = "Les jeux";
}

<h2 class="titleCenter">Le listing des jeux</h2>

<div class="row containerAllItems">
    @foreach (var console in Model)
    {
        <div class="row col-sm-12 col-lg-6">
            <h2 class="titleCenter">@console.Nom</h2>
            @{var userId = User.Identity.GetUserId();}
            @foreach (var jeu in console.Jeu)
            {
                <div class="blockItem col-sm-offset-1 col-sm-4">
                    <h3>@Html.ActionLink(jeu.Nom, "DetailsJeu", "Jeu", new { nomSeo = jeu.NomSeo }, null)</h3>
                    @Html.ActionLink("Laissez un avis pour ce jeu", "LaisserUnavis", "AvisJeu", new { nomSeo = jeu.NomSeo }, new { @class = "link" })
                    @if (userId != null)
                    {
                        if (BoutonVerification.BoutonAjoutJeuCollection(userId, jeu.Id))
                        {
                            <button class="btn btn-primary btn-xs addButton" type="button">@Html.ActionLink("Ajouter", "AjoutCollection", "Collection", new { id = jeu.Id, userID = userId, table = "jeuAssoPersonne" }, new { @class = "addLink" })</button>
                        }
                        else
                        {
                            <p class="alreadyHave">Ce jeu fait parti de votre collection</p>
                        }
                    }
                </div>
            }
        </div>
    }
</div>